Improve template repository handling and update errors/warnings

diff --git a/.github/workflows/nixpkgs-update.yml b/.github/workflows/nixpkgs-update.yml
--- a/.github/workflows/nixpkgs-update.yml
+++ b/.github/workflows/nixpkgs-update.yml
@@ -39,7 +39,7 @@ jobs:
     steps:
       - if: ${{ !matrix.package }}
         run: |
-          echo "::error file=README.md,title=No Repositories Configured::No repositories have been added to nixpkgs-update.yml. Please follow the directions in the README file at the root of this repository." 1>&2
+          echo "::error title=No Repositories Configured::No repositories have been added to nixpkgs-update.yml. Please follow the directions in the README file at the root of this repository." 1>&2
           exit 1
 
       - name: Restore nixpkgs cache
@@ -132,14 +132,14 @@ jobs:
         run: |
           set -euxo pipefail
 
-          if [ -z "${GITHUB_TOKEN:-""}" ]; then
-            echo "::error file=README.md,title=No PAT Configured::A PAT has not been added to this repository's secrets. Please follow the directions in the README file at the root of this repository." 1>&2
-            exit 1
+          GH_TOKEN_HEADER=""
+          if [ -n "${GITHUB_TOKEN:-}" ]; then
+            GH_TOKEN_HEADER="-H Authorization: token $GITHUB_TOKEN"
           fi
 
-          USER_INFO="$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/user)"
-          EMAIL_INFO="$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/user/emails)"
-          REPO_INFO="$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$REPO_STUB")"
+          USER_INFO="$(curl -s "$GH_TOKEN_HEADER" https://api.github.com/user || echo '{}')"
+          EMAIL_INFO="$(curl -s "$GH_TOKEN_HEADER" https://api.github.com/user/emails || echo '[]')"
+          REPO_INFO="$(curl -s "$GH_TOKEN_HEADER" "https://api.github.com/repos/$REPO_STUB" || echo '{}')"
 
           LOGIN="${LOGIN:-$(echo "$USER_INFO" | jq -r .login)}"
           NAME="${NAME:-$(echo "$USER_INFO" | jq -r .name)}"
@@ -157,6 +157,11 @@ jobs:
             IS_TEMPLATE_REPO="false"
             TEMPLATE_DEFAULT_BRANCH="$(echo "$REPO_INFO" | jq -r '.template_repository.default_branch')"
             TEMPLATE_FULL_NAME="$(echo "$REPO_INFO" | jq -r '.template_repository.full_name')"
+          fi
+
+          if [ "$IS_TEMPLATE_REPO" = "false" ] && [ -z "${GITHUB_TOKEN:-}" ]; then
+            echo "::error title=No PAT Configured::A PAT has not been added to this repository's secrets. Please follow the directions in the README file at the root of this repository." 1>&2
+            exit 1
           fi
 
           {
@@ -199,7 +204,7 @@ jobs:
 
           NIXPKGS_FIRST_RUN=0
           if [ ! -d "$NIXPKGS_LOCATION" ]; then
-            echo "::notice title=First Run::This is the first time this workflow is being run. Since the size of nixpkgs is over the cache limit, it will need to be compressed. This will take a long time."
+            echo "::warning title=First Run::This is the first time this workflow is being run. Since the size of nixpkgs is over the cache limit, it will need to be compressed. This will take a long time."
             NIXPKGS_FIRST_RUN=1
           fi
 
